"""Provision a brand-new customer: billing account, location account, mapping row.

This is the deliberate exception to find-or-reject, and it is worth being clear about
what it costs. Every one of the ~10,800 accounts in this org carries an
`LvtCustomerId__c`, which means accounts originate in VMS - Salesforce is downstream of
it. An account created here therefore carries a UUID that **VMS has never heard of**.

Consequences, stated rather than hidden:

  * The minted UUIDs will not match anything in VMS. When the customer is later set up
    there properly, a second Salesforce account will likely appear alongside this one.
  * Nothing here reconciles that. The account's Description records what happened so a
    human can merge the records, and that merge is a manual job someone has to do.

The structure mirrors what existing customers have, so orders resolve down one code path
regardless of whether the customer is new:

    Account "1 - Top/Mid Account"   <- billing, holds LvtCustomerId__c
      └── Account "2 - Location Account"  <- ship-to, holds LvtLocationId__c
    Location_Account_UUID_Mapping__c binding the two UUIDs

Matching is exact-name only. "Brasfield and Gorrie" will not match "Brasfield & Gorrie-
GA", so a customer who types their name differently gets a duplicate account. That is a
known limitation of having only a typed company name to work from.
"""

from __future__ import annotations

import uuid
from datetime import date

from .. import sfcli
from ..errors import ACCOUNT_AMBIGUOUS, Rejection

BILLING_RECORD_TYPE = "Top_Mid_Account"
LOCATION_RECORD_TYPE = "Location_Account"


def _escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "\\'")


def _record_type_id(developer_name: str, org: str) -> str:
    record = sfcli.query_one(
        "SELECT Id FROM RecordType WHERE SobjectType = 'Account' "
        f"AND DeveloperName = '{developer_name}'",
        org=org,
    )
    if not record:
        raise Rejection("PRODUCT_NOT_FOUND", f"no Account record type {developer_name!r}")
    return record["Id"]


def _address_fields(address: dict) -> dict:
    """Map a portal address onto Account billing AND shipping fields.

    Two org-specific constraints, both discovered the hard way:

      * State and Country picklists are enabled, splitting each into a free-text name
        field and a restricted code field. Writing "UT" to BillingState is rejected
        ("Please select a state from the list of valid states") - two-letter codes belong
        in BillingStateCode, which in turn requires a country code alongside it.
      * A validation rule enforces "Shipping Address Required", so billing alone will not
        save. The portal collects per-site shipping separately; here we mirror billing,
        which is right for the single-location v1 case.
    """
    street = address.get("street")
    city = address.get("city")
    zip_code = address.get("zip")
    state = (address.get("state") or "").strip()

    fields: dict = {}
    for prefix in ("Billing", "Shipping"):
        if street:
            fields[f"{prefix}Street"] = street
        if city:
            fields[f"{prefix}City"] = city
        if zip_code:
            fields[f"{prefix}PostalCode"] = zip_code
        if state:
            if len(state) == 2 and state.isalpha():
                fields[f"{prefix}StateCode"] = state.upper()
                # The state code is validated against the country, so set that too.
                # The portal is US-only (it validates 5-digit ZIPs).
                fields[f"{prefix}CountryCode"] = "US"
            else:
                fields[f"{prefix}State"] = state
    return fields


def _reconciliation_note(order_id: str, today: date) -> str:
    return (
        f"Created automatically from the LVT online order portal (order {order_id}) on "
        f"{today.isoformat()}. The LvtCustomerId/LvtLocationId on this record and its "
        "children were generated by Hermes and do NOT exist in VMS. This account must be "
        "reconciled with the customer's real VMS record, and merged if VMS later "
        "generates a separate Salesforce account."
    )


def find_billing_account(company_name: str, org: str) -> dict | None:
    """Exact-name lookup for an existing billing account."""
    name = company_name.strip()
    if not name:
        return None

    matches = sfcli.query(
        "SELECT Id, Name, LvtCustomerId__c FROM Account "
        f"WHERE Name = '{_escape(name)}' ORDER BY CreatedDate LIMIT 2",
        org=org,
    )
    if len(matches) > 1:
        raise Rejection(
            ACCOUNT_AMBIGUOUS,
            f"{len(matches)} accounts are named {name!r}; a human needs to pick one",
            field="submitted_by.company_name",
        )
    return matches[0] if matches else None


def _find_location_child(billing_account_id: str, org: str) -> dict | None:
    matches = sfcli.query(
        "SELECT Id, Name, LvtLocationId__c FROM Account "
        f"WHERE ParentId = '{billing_account_id}' AND LvtLocationId__c != null "
        "ORDER BY CreatedDate LIMIT 1",
        org=org,
    )
    return matches[0] if matches else None


def _create_mapping(customer_uuid: str, location_uuid: str, org: str) -> str:
    """Create the binding row. Field shape copied from existing rows in this org:
    Unique_Pairing_UUID__c mirrors the location UUID, and Validation_Concat__c is the two
    UUIDs concatenated with no separator (it is the object's unique key).
    """
    return sfcli.create(
        "Location_Account_UUID_Mapping__c",
        {
            "Billing_Account_UUID__c": customer_uuid,
            "Location_Account_UUID__c": location_uuid,
            "Unique_Pairing_UUID__c": location_uuid,
            "Validation_Concat__c": f"{customer_uuid}{location_uuid}",
        },
        org=org,
    )


def provision(submitted_by: dict, location: dict, order_id: str, org: str,
              *, today: date | None = None) -> dict:
    """Find or create the account structure for a new customer.

    Returns the same shape resolve.resolve produces, so downstream steps do not care
    which path the order took.

    Provisioning is three separate writes and Salesforce gives us no transaction across
    them, so a failure partway leaves records behind. That is not hypothetical: a
    validation rule requiring a shipping address applies to the location record type but
    not to Top/Mid, so an early version created the billing account and then died on the
    location account, orphaning it. On failure we now raise PARTIAL_CREATION naming every
    record created, so cleanup is one query rather than a hunt.
    """
    created: list[str] = []
    try:
        return _provision(submitted_by, location, order_id, org, created, today=today)
    except Rejection:
        raise
    except Exception as exc:  # noqa: BLE001 - re-raised with cleanup context
        raise Rejection(
            "PARTIAL_CREATION",
            f"account provisioning failed partway: {exc}. "
            + (f"Records created before the failure: {created}. " if created
               else "No records were created. ")
            + "Re-submitting with the same company name reuses a billing account created "
              "before the failure rather than duplicating it.",
            field="submitted_by.company_name",
        ) from exc


def _provision(submitted_by: dict, location: dict, order_id: str, org: str,
               created_records: list[str], *, today: date | None = None) -> dict:
    today = today or date.today()
    company_name = (submitted_by.get("company_name") or "").strip()
    address = submitted_by.get("billing_address") or {}

    existing = find_billing_account(company_name, org)

    if existing:
        billing_id = existing["Id"]
        customer_uuid = existing.get("LvtCustomerId__c")
        billing_created = False
        # An account that predates this flow may legitimately have no LVT id.
        if not customer_uuid:
            customer_uuid = str(uuid.uuid4())
            sfcli.run(
                ["data", "update", "record", "--sobject", "Account",
                 "--record-id", billing_id, "--target-org", org,
                 "--values", f'LvtCustomerId__c="{customer_uuid}"']
            )
    else:
        customer_uuid = str(uuid.uuid4())
        fields = {
            "Name": company_name,
            "RecordTypeId": _record_type_id(BILLING_RECORD_TYPE, org),
            "LvtCustomerId__c": customer_uuid,
            "Description": _reconciliation_note(order_id, today),
            **_address_fields(address),
        }
        billing_id = sfcli.create("Account", fields, org=org)
        billing_created = True
        created_records.append(billing_id)

    # Reuse an existing location child rather than adding one per order.
    child = _find_location_child(billing_id, org)
    if child:
        location_id = child["Id"]
        location_uuid = child["LvtLocationId__c"]
        location_name = child["Name"]
        location_created = False
    else:
        location_uuid = str(uuid.uuid4())
        zip_code = location.get("zip_code") or address.get("zip")
        suffix = zip_code or "Site 1"
        location_name = f"{company_name} - {suffix}"
        # Inherit the billing address, overriding the postcode with the site's own.
        location_address = {**address, "zip": zip_code or address.get("zip")}
        location_id = sfcli.create(
            "Account",
            {
                "Name": location_name,
                "RecordTypeId": _record_type_id(LOCATION_RECORD_TYPE, org),
                "ParentId": billing_id,
                "LvtLocationId__c": location_uuid,
                "Description": _reconciliation_note(order_id, today),
                **_address_fields(location_address),
            },
            org=org,
        )
        location_created = True
        created_records.append(location_id)

    # The resolver checks for this row, so it has to exist even when both accounts did.
    mapping_exists = sfcli.count(
        "SELECT COUNT(Id) FROM Location_Account_UUID_Mapping__c "
        f"WHERE Billing_Account_UUID__c = '{_escape(customer_uuid)}' "
        f"AND Location_Account_UUID__c = '{_escape(location_uuid)}'",
        org=org,
    )
    mapping_created = False
    if not mapping_exists:
        created_records.append(_create_mapping(customer_uuid, location_uuid, org))
        mapping_created = True

    return {
        "billing_account_id": billing_id,
        "billing_account_name": company_name or (existing or {}).get("Name"),
        "lvt_customer_id": customer_uuid,
        "lvt_location_id": location_uuid,
        "provisioned": {
            "billing_account_created": billing_created,
            "location_account_created": location_created,
            "location_account_name": location_name,
            "mapping_created": mapping_created,
            "needs_vms_reconciliation": billing_created,
            "created_record_ids": created_records,
        },
        "locations": [
            {
                **location,
                "lvt_location_id": location_uuid,
                "account_id": location_id,
                "account_name": location_name,
            }
        ],
    }
